"""Deterministic mock LLM — no network, no API key.

It is not a language model; it is a tiny rule-based stand-in whose only job is to
exercise the *harness* end-to-end (the reason -> act -> observe loop, tool
calling, citations, and the HITL gate) so a reviewer can run and test the whole
system offline. Behaviour:

- If the user clearly wants to save something -> request the `save_note` action.
- Otherwise, on the first turn -> request `search_knowledge_base`.
- After a tool result is present -> emit a grounded final answer that quotes the
  retrieved passages and lists their sources.
"""

from __future__ import annotations

import re
from typing import Any

from app.llm.base import AssistantTurn, ToolCall, ToolSpec

_SAVE_RE = re.compile(r"\b(save|remember|bookmark|note this|write.{0,6}down)\b", re.I)
_SOURCE_RE = re.compile(r"\[source: ([^\]]+)\]")


class MockClient:
    name = "mock"

    def complete(
        self,
        system: str,
        messages: list[dict[str, Any]],
        tools: list[ToolSpec],
    ) -> AssistantTurn:
        tool_names = {t.name for t in tools}
        last_user = self._last_user(messages)
        tool_results = self._tool_results(messages)

        # --- HITL action path -------------------------------------------
        if last_user and _SAVE_RE.search(last_user) and "save_note" in tool_names:
            if not any(r["name"] == "save_note" for r in tool_results):
                title = (last_user[:48] + "...") if len(last_user) > 48 else last_user
                return AssistantTurn(
                    text="You asked me to save this — proposing a note.",
                    tool_calls=[
                        ToolCall(
                            id="call_save_1",
                            name="save_note",
                            arguments={"title": title, "content": last_user},
                        )
                    ],
                )
            saved = tool_results[-1]["content"]
            return AssistantTurn(text=f"Done. {saved}")

        # --- RAG retrieval path -----------------------------------------
        if not tool_results and "search_knowledge_base" in tool_names and last_user:
            return AssistantTurn(
                text="Let me check the knowledge base.",
                tool_calls=[
                    ToolCall(
                        id="call_search_1",
                        name="search_knowledge_base",
                        arguments={"query": last_user, "top_k": 4},
                    )
                ],
            )

        # --- Grounded answer from retrieved context ---------------------
        if tool_results:
            retrieved = "\n\n".join(r["content"] for r in tool_results)
            sources = sorted({s.split(" / ")[0].strip() for s in _SOURCE_RE.findall(retrieved)})
            snippet = self._snippet(retrieved)
            answer = (
                f"Based on the knowledge base:\n\n{snippet}"
                "\n\n(Generated by the deterministic mock LLM — set "
                "ANTHROPIC_API_KEY and LLM_PROVIDER=anthropic for real answers.)"
            )
            if sources:
                answer += "\n\nSources: " + ", ".join(sources)
            return AssistantTurn(text=answer)

        return AssistantTurn(
            text="I can answer questions about the agentic-AI knowledge base. "
            "Ask me about MCP, RAG, Agent Skills, or harnesses."
        )

    # -- helpers ---------------------------------------------------------
    @staticmethod
    def _last_user(messages: list[dict[str, Any]]) -> str:
        for m in reversed(messages):
            if m["role"] == "user":
                return m["content"]
        return ""

    @staticmethod
    def _tool_results(messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [m for m in messages if m["role"] == "tool"]

    @staticmethod
    def _snippet(text: str, limit: int = 600) -> str:
        text = _SOURCE_RE.sub("", text).strip()
        text = re.sub(r"\n-{3,}\n", "\n\n", text)
        text = re.sub(r"\(similarity [0-9.]+\)", "", text)
        text = re.sub(r"\n{3,}", "\n\n", text).strip()
        return text[:limit] + ("..." if len(text) > limit else "")
